// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230222190027_AddNumVillaTable")]
    partial class AddNumVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.NumVilla", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EspecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Villaid")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("Villaid");

                    b.ToTable("NumVilla");
                });

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("squaremeter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreate = new DateTime(2023, 2, 22, 14, 0, 26, 837, DateTimeKind.Local).AddTicks(125),
                            DateUpdate = new DateTime(2023, 2, 22, 14, 0, 26, 837, DateTimeKind.Local).AddTicks(191),
                            Detail = "Detail of villa...",
                            ImageURL = "",
                            Name = "Villa Real",
                            Occupants = 10,
                            Rate = 10000.0,
                            amenidad = "",
                            squaremeter = 150
                        },
                        new
                        {
                            Id = 2,
                            DateCreate = new DateTime(2023, 2, 22, 14, 0, 26, 837, DateTimeKind.Local).AddTicks(196),
                            DateUpdate = new DateTime(2023, 2, 22, 14, 0, 26, 837, DateTimeKind.Local).AddTicks(198),
                            Detail = "beautifull 3 pool",
                            ImageURL = "",
                            Name = "Villa premiun",
                            Occupants = 4,
                            Rate = 5240.0,
                            amenidad = "",
                            squaremeter = 120
                        });
                });

            modelBuilder.Entity("MagicVilla_API.Models.NumVilla", b =>
                {
                    b.HasOne("MagicVilla_API.Models.Villa", "villa")
                        .WithMany()
                        .HasForeignKey("Villaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("villa");
                });
#pragma warning restore 612, 618
        }
    }
}
